version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.1
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: cimg/postgres:14.1
        # environment:
        #   POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          name: debug
          command: pwd
      - run:
          name: install dependancies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python manage.py test

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
