version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.1
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: example
    steps:
      - checkout
      - run:
          name: install dependancies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: pylint my_media/ media_organizer/
      - run:
          name: run tests
          command: python manage.py test
      - store_test_results:
          path: test_results

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
